name: Terraform » VPC Creation (Multi-env)

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  terraform-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP (Dev)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_DEV }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Dev)
        run: terraform -chdir=env/dev init

      - name: Terraform Plan (Dev)
        run: terraform -chdir=env/dev plan -out=tfplan

      - name: Terraform Apply (Dev)
        run: terraform -chdir=env/dev apply -input=false tfplan

  terraform-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP (Test)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_TEST }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Test)
        run: terraform -chdir=env/test init

      - name: Terraform Plan (Test)
        run: terraform -chdir=env/test plan -out=tfplan

      - name: Terraform Apply (Test)
        run: terraform -chdir=env/test apply -input=false tfplan

  terraform-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod   # 👈 will wait for approval
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP (Prod)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_PROD }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Prod)
        run: terraform -chdir=env/prod init

      - name: Terraform Plan (Prod)
        run: terraform -chdir=env/prod plan -out=tfplan

      - name: Terraform Apply (Prod)
        run: terraform -chdir=env/prod apply -input=false tfplan
